### ISSUE TITLE
New versione alpine3.7 and python3.10

### ISSUE THREAD

**Issue by ianustec** [Jonarod/tensorflow_lite_alpine#2]
Hello,

I've been trying for several days to install tensorflow_runtime on an Alpine system using Python3.10, all without success.

Can you give me a hand?
I'm sure it can be useful for other people too.

Thank you

**Comment by Jonarod** [comment]
Hello, Sorry I don't understand your issue.
What kind of errors do you get after following the build process I described in the README ?

**Comment by ianustec** [comment]
Hi,

I need a .whl file (or other some kind of file) to install as a python module.

As apk add 'hosted_whl_file'

Many thanks

**Comment by Jonarod** [comment]
If you don't detail the errors you found by following all the steps in the README I am afraid I will not be able to help.

**Comment by ianustec** [comment]
Sure, sorry.

1. I got .so file following QuickStart 
2. I can't import .so file as python module so I followed this suggestion https://stackoverflow.com/a/13466708 
```
# tensorflow_runtime.py in the same location of app.py file
def __bootstrap__():
   global __bootstrap__, __loader__, __file__
   import sys, pkg_resources, imp
   __file__ = pkg_resources.resource_filename(__name__,'libtensorflowlite_c.so')
   __loader__ = None; del __bootstrap__, __loader__
   imp.load_dynamic(__name__,__file__)
__bootstrap__()
```

3. I got this errore in app.py
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 993, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 775, in read_app
    self.read_app(file)
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 784, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/[...]/app.py", line 11, in <module>
    import tensorflow_runtime
  File "/[...]/tensorflow_runtime.py", line 7, in <module>
    __bootstrap__()
  File "/[...]/tensorflow_runtime.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/usr/lib/python3.10/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: Error relocating /[...]/libtensorflowlite_c.so: unsupported relocation type 7
```

**Comment by ianustec** [comment]
I tried to import .so directly, same error :(

**Comment by Jonarod** [comment]
I am afraid this is completely out of the scope of this project my friend. Check on Stackoverflow maybe...

However I do encourage you to adapt the builder to your specific needs [here](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile). Maybe trying new versions of TF_Lite and specifying your Python version: eventually this will produce a new .so file maybe more adapted to your actual needs.

That being said, I will close this for now.

Good luck !

**Comment by ianustec** [comment]
> I am afraid this is completely out of the scope of this project my friend. Check on Stackoverflow maybe...
> 
> However I do encourage you to adapt the builder to your specific needs [here](https://github.com/Jonarod/tensorflow_lite_alpine/blob/master/builder/Dockerfile). Maybe trying new versions of TF_Lite and specifying your Python version: eventually this will produce a new .so file maybe more adapted to your actual needs.
> 
> That being said, I will close this for now.
> 
> Good luck !

Hello,

I already tried but tf never supports make as a builder and the build fails.

I'm in trouble because I don't have this kind of skill.

many thanks all the same.
